### ISSUE TITLE
Implement logic to track translation status for project

### ISSUE THREAD

**Issue by Judis** [Judis/tr_api#16]
Each time when we return project object we should return project statistic too.
This statistic should contain:
- total count of translation keys
- count of not verified keys
- count of verified keys
- count of translated keys (`verified` + `unverified`)
- count of untranslated keys
- count of keys with status `need_check`

So, we should implement logic to calculate that stats and store it at project model.
We should add stats field into Project model and extend current returned object to pass that stat values.

**Comment by EevanW** [comment]
We share statistical fields between project and locales.
To project:
- total_count_of_translation_keys
To locale:
- count_of_not_verified_keys - inc/decremental
- count_of_verified_keys - inc/decremental
- count_of_translated_keys - inc/decremental
- count_of_untranslated_keys - difference between total_count_of_translation_keys & count_of_translated_key, also go around and recalculation when adding a new key, or if the key is changed to the “removed” status

- count_of_keys_with_status_need_check -  inc/decremental
Also the service function of the recalculation of all statuses in the project.
