### ISSUE TITLE
Move status field from TranslationKey into Translation model

### ISSUE THREAD

**Issue by Judis** [Judis/tr_api#18]
After split Translation Key into two separated models, we are miss Status field at Translation Key model, this is not right.
We should move this field into Translation model and connect Enum declaration.
Possible statuses:
`empty` - translation key is created, but translation is empty
`unverified` - translation is filled, but not confirmed by reviewer
`verified` - translation is checked and confirmed by reviewer
`need_check` - translation at default locale was changed, and current translation can be not actual

**Comment by EevanW** [comment]
Merged by pull request #24
